
dist: trusty
sudo: required

language: cpp

compiler:
  - gcc
  
addons:
apt:
  packages:
    - gnuefi

script:
  - mkdir example-build
  - cd example-build
  - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ../example
  - make
  
